### ISSUE TITLE
AZ-104 Additions

### ISSUE THREAD

**Issue by jamesdplee** [jamesdplee/cloudlee-roadmap#17]
Adding quizzes, case studies, click-to-deploy templates for demos, and some updates.

**Comment by ajay426344** [comment]
By when can we expect these updates go live, @jamesdplee . As I'm planning on taking AZ-104 as my next certification.

**Comment by jamesdplee** [comment]
> w

The quizzes are now live. I'll be adding case studies next. 

General updates are always generally ongoing in terms of fixing content with changes. If there's anything you need to know, I'll note it in the description beneath the video while I'm making any updates. You can of course expect some basic UI changes as with all cloud providers too - and I'll be fixing those over time as well.

**Comment by MikelMZ** [comment]
Hello @jamesdplee when we can expect case studies uploaded? Thanks,

**Comment by jamesdplee** [comment]
I’m planning to start uploads over the coming days. There have been some delays, sorry. But the case studies are coming soon!
________________________________
